<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <title>Printable Report - {{ $report->title }}</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 24px; color: #222; }
        h1 { margin-bottom: 4px; }
        .meta { margin-bottom: 12px; color: #555; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background: #f4f4f4; }
        .center { text-align: center; }
        .small { font-size: 0.9em; color: #666; }
        @media print { .no-print { display: none; } }
    </style>
</head>
<body>
    <div class="no-print" style="margin-bottom:12px;">
        <button onclick="window.print()">Print</button>
        <a href="{{ url()->previous() }}">Back</a>
    </div>

    <h1>{{ $report->title }}</h1>
    <div class="meta small">
        Generated by: {{ $report->generatedBy->name ?? 'System' }} | Generated at: {{ $report->generated_at ? $report->generated_at->format('M d, Y g:i A') : 'N/A' }}
    </div>

    @if($report->type === \App\Models\Report::TYPE_ADMISSIONS)
        <h2>Admissions Summary</h2>
        <p>Admitted patients in period: {{ $report->data['period']['from'] ?? 'N/A' }} to {{ $report->data['period']['to'] ?? 'N/A' }}</p>
        <p>Total unique patients admitted: <strong>{{ $report->data['admitted_patient_count'] ?? 0 }}</strong></p>
        <p>Total admissions: <strong>{{ $report->data['admissions_count'] ?? 0 }}</strong></p>

        @if(!empty($report->data['admissions']))
            <table>
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Admission #</th>
                        <th>Admission Date</th>
                        <th>Discharge Date</th>
                        <th>Patient No</th>
                        <th>Patient Name</th>
                        <th>Room</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($report->data['admissions'] as $idx => $a)
                    <tr>
                        <td class="center">{{ $idx + 1 }}</td>
                        <td>{{ $a['admission_number'] ?? '' }}</td>
                        <td>{{ $a['admission_date'] ?? '' }}</td>
                        <td>{{ $a['discharge_date'] ?? '' }}</td>
                        <td>{{ $a['patient']['patient_no'] ?? '' }}</td>
                        <td>{{ $a['patient']['name'] ?? '' }}</td>
                        <td>{{ $a['room_no'] ?? '' }}</td>
                        <td>{{ ucfirst($a['status'] ?? '') }}</td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No admissions found for the selected period.</p>
        @endif
    @else
        <h2>Report Data</h2>
        <pre>{{ json_encode($report->data, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES) }}</pre>
    @endif
</body>
</html>
