<div class="report-details">
    <div class="report-header">
        <h4>{{ $report->title }}</h4>
        <div class="report-meta">
            <span class="type-badge type-{{ $report->type }}">{{ $report->formatted_type }}</span>
            <span class="status-badge status-{{ $report->status }}">{{ ucfirst($report->status) }}</span>
        </div>
    </div>
    
    <div class="report-info">
        <div class="info-grid">
            <div class="info-item">
                <label>Generated By:</label>
                <span>{{ $report->generatedBy->name ?? 'System' }}</span>
            </div>
            <div class="info-item">
                <label>Generated At:</label>
                <span>{{ $report->generated_at ? $report->generated_at->format('M d, Y g:i A') : 'N/A' }}</span>
            </div>
            <div class="info-item">
                <label>Description:</label>
                <span>{{ $report->description ?? 'No description available' }}</span>
            </div>
        </div>
    </div>
    
    @if($report->data)
    <div class="report-data">
        <h5>Report Data</h5>
        
        @if($report->type === 'user_activity')
            <div class="data-section">
                <h6>Summary</h6>
                <div class="summary-grid">
                    <div class="summary-item">
                        <span class="label">Period:</span>
                        <span class="value">{{ $report->data['period']['from'] ?? 'N/A' }} to {{ $report->data['period']['to'] ?? 'N/A' }}</span>
                    </div>
                    <div class="summary-item">
                        <span class="label">Total Users:</span>
                        <span class="value">{{ $report->data['total_users'] ?? 0 }}</span>
                    </div>
                    <div class="summary-item">
                        <span class="label">New Users:</span>
                        <span class="value">{{ $report->data['new_users'] ?? 0 }}</span>
                    </div>
                </div>
                
                @if(isset($report->data['summary']))
                <h6>Users by Role</h6>
                <div class="role-breakdown">
                    @foreach($report->data['summary'] as $role => $count)
                    <div class="role-item">
                        <span class="role-name">{{ ucfirst(str_replace('_', ' ', $role)) }}:</span>
                        <span class="role-count">{{ $count }}</span>
                    </div>
                    @endforeach
                </div>
                @endif
            </div>
            
        @elseif($report->type === 'user_registration')
            <div class="data-section">
                <h6>Registration Summary</h6>
                <div class="summary-grid">
                    <div class="summary-item">
                        <span class="label">Period:</span>
                        <span class="value">{{ $report->data['period']['from'] ?? 'N/A' }} to {{ $report->data['period']['to'] ?? 'N/A' }}</span>
                    </div>
                    <div class="summary-item">
                        <span class="label">Total Registrations:</span>
                        <span class="value">{{ $report->data['total_registrations'] ?? 0 }}</span>
                    </div>
                </div>
                
                @if(isset($report->data['registrations']) && count($report->data['registrations']) > 0)
                <h6>Recent Registrations</h6>
                <div class="registrations-list">
                    @foreach(array_slice($report->data['registrations'], 0, 10) as $registration)
                    <div class="registration-item">
                        <div class="user-info">
                            <strong>{{ $registration['name'] ?? 'N/A' }}</strong>
                            <span class="email">{{ $registration['email'] ?? 'N/A' }}</span>
                        </div>
                        <div class="reg-meta">
                            <span class="role-badge role-{{ $registration['role'] ?? 'user' }}">
                                {{ ucfirst($registration['role'] ?? 'User') }}
                            </span>
                            <span class="date">{{ \Carbon\Carbon::parse($registration['created_at'])->format('M d, Y') }}</span>
                        </div>
                    </div>
                    @endforeach
                </div>
                @endif
            </div>
            
        @elseif($report->type === 'system_log')
            <div class="data-section">
                <h6>System Log Summary</h6>
                <div class="summary-grid">
                    <div class="summary-item">
                        <span class="label">Period:</span>
                        <span class="value">{{ $report->data['period']['from'] ?? 'N/A' }} to {{ $report->data['period']['to'] ?? 'N/A' }}</span>
                    </div>
                    <div class="summary-item">
                        <span class="label">Total Reports:</span>
                        <span class="value">{{ $report->data['total_reports'] ?? 0 }}</span>
                    </div>
                </div>
                
                @if(isset($report->data['reports_by_type']))
                <h6>Reports by Type</h6>
                <div class="type-breakdown">
                    @foreach($report->data['reports_by_type'] as $type => $count)
                    <div class="type-item">
                        <span class="type-name">{{ ucfirst(str_replace('_', ' ', $type)) }}:</span>
                        <span class="type-count">{{ $count }}</span>
                    </div>
                    @endforeach
                </div>
                @endif
            </div>
            
        @else
            <div class="data-section">
                <div class="raw-data">
                    <pre>{{ json_encode($report->data, JSON_PRETTY_PRINT) }}</pre>
                </div>
            </div>
        @endif
    </div>
    @else
    <div class="no-data">
        <p>No data available for this report.</p>
    </div>
    @endif
</div>
