<div class="report-details">
    <div class="report-header">
        <h4><?php echo e($report->title); ?></h4>
        <div class="report-meta">
            <span class="type-badge type-<?php echo e($report->type); ?>"><?php echo e($report->formatted_type); ?></span>
            <span class="status-badge status-<?php echo e($report->status); ?>"><?php echo e(ucfirst($report->status)); ?></span>
        </div>
    </div>
    
    <div class="report-info">
        <div class="info-grid">
            <div class="info-item">
                <label>Generated By:</label>
                <span><?php echo e($report->generatedBy->name ?? 'System'); ?></span>
            </div>
            <div class="info-item">
                <label>Generated At:</label>
                <span><?php echo e($report->generated_at ? $report->generated_at->format('M d, Y g:i A') : 'N/A'); ?></span>
            </div>
            <div class="info-item">
                <label>Description:</label>
                <span><?php echo e($report->description ?? 'No description available'); ?></span>
            </div>
        </div>
    </div>
    
    <?php if($report->data): ?>
    <div class="report-data">
        <h5>Report Data</h5>
        
        <?php if($report->type === 'user_activity'): ?>
            <div class="data-section">
                <h6>Summary</h6>
                <div class="summary-grid">
                    <div class="summary-item">
                        <span class="label">Period:</span>
                        <span class="value"><?php echo e($report->data['period']['from'] ?? 'N/A'); ?> to <?php echo e($report->data['period']['to'] ?? 'N/A'); ?></span>
                    </div>
                    <div class="summary-item">
                        <span class="label">Total Users:</span>
                        <span class="value"><?php echo e($report->data['total_users'] ?? 0); ?></span>
                    </div>
                    <div class="summary-item">
                        <span class="label">New Users:</span>
                        <span class="value"><?php echo e($report->data['new_users'] ?? 0); ?></span>
                    </div>
                </div>
                
                <?php if(isset($report->data['summary'])): ?>
                <h6>Users by Role</h6>
                <div class="role-breakdown">
                    <?php $__currentLoopData = $report->data['summary']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $role => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <div class="role-item">
                        <span class="role-name"><?php echo e(ucfirst(str_replace('_', ' ', $role))); ?>:</span>
                        <span class="role-count"><?php echo e($count); ?></span>
                    </div>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </div>
                <?php endif; ?>
            </div>
            
        <?php elseif($report->type === 'user_registration'): ?>
            <div class="data-section">
                <h6>Registration Summary</h6>
                <div class="summary-grid">
                    <div class="summary-item">
                        <span class="label">Period:</span>
                        <span class="value"><?php echo e($report->data['period']['from'] ?? 'N/A'); ?> to <?php echo e($report->data['period']['to'] ?? 'N/A'); ?></span>
                    </div>
                    <div class="summary-item">
                        <span class="label">Total Registrations:</span>
                        <span class="value"><?php echo e($report->data['total_registrations'] ?? 0); ?></span>
                    </div>
                </div>
                
                <?php if(isset($report->data['registrations']) && count($report->data['registrations']) > 0): ?>
                <h6>Recent Registrations</h6>
                <div class="registrations-list">
                    <?php $__currentLoopData = array_slice($report->data['registrations'], 0, 10); $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $registration): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <div class="registration-item">
                        <div class="user-info">
                            <strong><?php echo e($registration['name'] ?? 'N/A'); ?></strong>
                            <span class="email"><?php echo e($registration['email'] ?? 'N/A'); ?></span>
                        </div>
                        <div class="reg-meta">
                            <span class="role-badge role-<?php echo e($registration['role'] ?? 'user'); ?>">
                                <?php echo e(ucfirst($registration['role'] ?? 'User')); ?>

                            </span>
                            <span class="date"><?php echo e(\Carbon\Carbon::parse($registration['created_at'])->format('M d, Y')); ?></span>
                        </div>
                    </div>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </div>
                <?php endif; ?>
            </div>
            
        <?php elseif($report->type === 'system_log'): ?>
            <div class="data-section">
                <h6>System Log Summary</h6>
                <div class="summary-grid">
                    <div class="summary-item">
                        <span class="label">Period:</span>
                        <span class="value"><?php echo e($report->data['period']['from'] ?? 'N/A'); ?> to <?php echo e($report->data['period']['to'] ?? 'N/A'); ?></span>
                    </div>
                    <div class="summary-item">
                        <span class="label">Total Reports:</span>
                        <span class="value"><?php echo e($report->data['total_reports'] ?? 0); ?></span>
                    </div>
                </div>
                
                <?php if(isset($report->data['reports_by_type'])): ?>
                <h6>Reports by Type</h6>
                <div class="type-breakdown">
                    <?php $__currentLoopData = $report->data['reports_by_type']; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $type => $count): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
                    <div class="type-item">
                        <span class="type-name"><?php echo e(ucfirst(str_replace('_', ' ', $type))); ?>:</span>
                        <span class="type-count"><?php echo e($count); ?></span>
                    </div>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
                </div>
                <?php endif; ?>
            </div>
            
        <?php else: ?>
            <div class="data-section">
                <div class="raw-data">
                    <pre><?php echo e(json_encode($report->data, JSON_PRETTY_PRINT)); ?></pre>
                </div>
            </div>
        <?php endif; ?>
    </div>
    <?php else: ?>
    <div class="no-data">
        <p>No data available for this report.</p>
    </div>
    <?php endif; ?>
</div>
<?php /**PATH D:\xampp\htdocs\DrRomelCruzHP\resources\views\admin\reports\show.blade.php ENDPATH**/ ?>