<?php

return [
    // Key => template definition
    'hematology' => [
        'title' => 'Hematology Laboratory Result Form',
        'code'  => 'HEM',
        'fields' => [
            ['key'=>'sex','label'=>'Sex','unit'=>'','ref'=>'M/F'],
            ['key'=>'wbc','label'=>'WBC','unit'=>'/L','ref'=>'4.0 - 10.0'],
            ['key'=>'lymph_abs','label'=>'Lymph#','unit'=>'/L','ref'=>'0.8 - 4.0'],
            ['key'=>'mid_abs','label'=>'Mid#','unit'=>'/L','ref'=>'0.1 - 1.5'],
            ['key'=>'gran_abs','label'=>'Gran#','unit'=>'/L','ref'=>'2.0 - 7.0'],
            ['key'=>'lymph_pct','label'=>'Lymph%','unit'=>'%','ref'=>'20.0 - 40.0'],
            ['key'=>'mid_pct','label'=>'Mid%','unit'=>'%','ref'=>'3.0 - 15.0'],
            ['key'=>'gran_pct','label'=>'Gran%','unit'=>'%','ref'=>'50.0 - 70.0'],
            ['key'=>'rbc','label'=>'RBC','unit'=>'/L','ref'=>'3.50 - 5.50'],
            ['key'=>'hgb','label'=>'HGB','unit'=>'g/L','ref'=>'110 - 160'],
            ['key'=>'hct','label'=>'HCT','unit'=>'%','ref'=>'37.0 - 54.0'],
            ['key'=>'plt','label'=>'PLT','unit'=>'/L','ref'=>'100 - 300'],
            ['key'=>'clotting_time','label'=>'CLOTTING TIME','unit'=>'Min;Sec','ref'=>'2"00" - 7"00"'],
            ['key'=>'bleeding_time','label'=>'BLEEDING TIME','unit'=>'Min;Sec','ref'=>'1"00" - 5"00"'],
        ],
    ],
    'blood_typing' => [
        'title' => 'Blood Typing Result Form',
        'code' => 'BT',
        'fields' => [
            ['key'=>'abo','label'=>'ABO Group','unit'=>'','ref'=>''],
            ['key'=>'rh','label'=>'Rh Factor','unit'=>'','ref'=>''],
        ],
    ],
    'fecal_occult' => [
        'title' => 'Fecal Occult Blood Test Result Form',
        'code' => 'FOBT',
        'fields' => [ ['key'=>'result','label'=>'Result','unit'=>'','ref'=>'Negative'] ],
    ],
    'pregnancy' => [
        'title' => 'Pregnancy Test Result Form',
        'code' => 'PT',
        'fields' => [ ['key'=>'hcg','label'=>'HCG','unit'=>'','ref'=>'Negative'] ],
    ],
    'urine_analysis' => [
        'title' => 'Urine Analysis Result Form',
        'code' => 'UA',
        'sections' => [
            'PHYSICAL CHARACTERISTICS' => [
                ['key'=>'color','label'=>'COLOR'],
                ['key'=>'transparency','label'=>'TRANSPARENCY'],
                ['key'=>'reaction','label'=>'REACTION/pH'],
                ['key'=>'specific_gravity','label'=>'Specific Gravity'],
                ['key'=>'albumin','label'=>'ALBUMIN'],
                ['key'=>'glucose','label'=>'GLUCOSE'],
            ],
            'MICROSCOPIC FINDINGS - CELLS' => [
                ['key'=>'rbc','label'=>'RED BLOOD CELLS'],
                ['key'=>'pus','label'=>'PUS CELLS'],
                ['key'=>'epithelial','label'=>'EPITHELIAL CELLS'],
                ['key'=>'mucus','label'=>'MUCOUS THREAD'],
                ['key'=>'yeast','label'=>'YEAST CELLS'],
                ['key'=>'preg_test','label'=>'PREGNANCY TEST'],
            ],
            'MICROSCOPIC FINDINGS - OTHERS' => [
                ['key'=>'a_phosphates','label'=>'A. PHOSPHATES'],
                ['key'=>'bacteria','label'=>'BACTERIA'],
                ['key'=>'cast','label'=>'CAST'],
                ['key'=>'oval_fat','label'=>'OVAL FAT BODY'],
                ['key'=>'coc','label'=>'CoC'],
                ['key'=>'uric_crystal','label'=>'URIC CRYSTAL'],
                ['key'=>'f_vaginalis','label'=>'F. VAGINALIS'],
            ],
        ],
    ],
    'fecal_analysis' => [
        'title' => 'Fecal Analysis Result Form',
        'code' => 'FA',
        'sections' => [
            'PHYSICAL CHARACTERISTICS' => [
                ['key'=>'color','label'=>'COLOR'],
                ['key'=>'consistency','label'=>'CONSISTENCY'],
            ],
            'MICROSCOPIC FINDINGS' => [
                ['key'=>'red_bc','label'=>'RED BLOOD CELL'],
                ['key'=>'pus_cell','label'=>'PUS CELL'],
                ['key'=>'parasite','label'=>'PARASITE'],
                ['key'=>'bacteria','label'=>'BACTERIA'],
                ['key'=>'yeast','label'=>'YEAST'],
                ['key'=>'occult','label'=>'OCCULT BLOOD TEST'],
            ],
        ],
    ],
    'clinical_chemistry' => [
        'title' => 'Clinical Chemistry Laboratory Result Form',
        'code' => 'CC',
        'fields' => [
            ['key'=>'glucose_rbs','label'=>'GLUCOSE (RBS)','unit'=>'mmol/L','ref'=>'3.85 - 6.05'],
            ['key'=>'glucose_fbs','label'=>'GLUCOSE (FBS)','unit'=>'mg/dl','ref'=>'70 - 110'],
            ['key'=>'cholesterol','label'=>'CHOLESTEROL','unit'=>'mmol/L','ref'=>'3.87 - 6.50'],
            ['key'=>'uric_acid','label'=>'URIC ACID (MALE)','unit'=>'mmol/L','ref'=>'3.5 - 7.2'],
            ['key'=>'uric_acid_female','label'=>'URIC ACID (FEMALE)','unit'=>'mmol/L','ref'=>'2.6 - 6.0'],
            ['key'=>'creatinine','label'=>'CREATININE','unit'=>'mmol/L','ref'=>'61.88 - 132.6'],
            ['key'=>'bun','label'=>'BUN/UREA NITROGEN','unit'=>'mmol/L','ref'=>'2.5 - 7.14'],
            ['key'=>'triglycerides','label'=>'TRIGLYCERIDES','unit'=>'mmol/L','ref'=>'0.45 - 1.69'],
            ['key'=>'hdl','label'=>'HDL CHOLESTEROL','unit'=>'mmol/L','ref'=>'0.78 - 1.95'],
            ['key'=>'ldl','label'=>'LDL CHOLESTEROL','unit'=>'mmol/L','ref'=>'2.59 - 4.90'],
            ['key'=>'sodium','label'=>'SODIUM','unit'=>'mmol/L','ref'=>'135 - 145'],
            ['key'=>'potassium','label'=>'POTASSIUM','unit'=>'mmol/L','ref'=>'3.5 - 5.3'],
            ['key'=>'chloride','label'=>'CHLORIDE','unit'=>'mmol/L','ref'=>'98.0 - 107.0'],
            ['key'=>'ionized_calcium','label'=>'IONIZE CALCIUM','unit'=>'mmol/L','ref'=>'1.13 - 1.32'],
            ['key'=>'sgpt','label'=>'SGPT/ALT','unit'=>'U/L','ref'=>'10.0 - 40.0'],
            ['key'=>'sgot','label'=>'SGOT/AST','unit'=>'U/L','ref'=>'5.0 - 35.0'],
        ],
    ],
    'misc_basic' => [
        'title' => 'Miscellaneous Laboratory Result Form',
        'code' => 'MISC',
        'fields' => [
            ['key'=>'trop_i','label'=>'TROPONIN I','unit'=>'ng/mL','ref'=>'< 0.30'],
            ['key'=>'hba1c','label'=>'HbA1c','unit'=>'%','ref'=>'< 6.5%'],
            ['key'=>'ferritin_women','label'=>'FERRITIN WOMEN','unit'=>'ng/mL','ref'=>'13 - 150'],
            ['key'=>'ferritin_men','label'=>'FERRITIN MEN','unit'=>'ng/mL','ref'=>'30 - 400'],
            ['key'=>'cea','label'=>'CEA NON-SMOKER','unit'=>'ng/mL','ref'=>'4'],
            ['key'=>'cea_smoker','label'=>'CEA SMOKER','unit'=>'ng/mL','ref'=>'5'],
            ['key'=>'crp','label'=>'CRP','unit'=>'mg/L','ref'=>'10'],
            ['key'=>'hscrp','label'=>'hsCRP','unit'=>'mg/L','ref'=>'< 1.0'],
            ['key'=>'afp','label'=>'AFP','unit'=>'ng/mL','ref'=>'>20'],
            ['key'=>'rf_igm','label'=>'RF - IgM','unit'=>'IU/mL','ref'=>'15'],
            ['key'=>'d_dimer','label'=>'D-DIMER','unit'=>'ng/mL','ref'=>'500'],
        ],
    ],
    'misc_finecare' => [
        'title' => 'Miscellaneous Laboratory Result Form (Finecare Machine)',
        'code' => 'MISC_FC',
        'fields' => [
            ['key'=>'ck_mb','label'=>'CK-MB','unit'=>'ng/mL','ref'=>'0.0 - 5.0'],
            ['key'=>'trop_i','label'=>'TROPONIN I','unit'=>'ng/mL','ref'=>'0.0 - 0.3'],
            ['key'=>'psa','label'=>'PSA','unit'=>'ng/mL','ref'=>'<4 (normal)'],
            ['key'=>'procalcitonin','label'=>'PROCALCITONIN (PCT)','unit'=>'ng/mL','ref'=>'<0.5 normal'],
            ['key'=>'d_dimer','label'=>'D-DIMER','unit'=>'mg/L','ref'=>'<0.5'],
        ],
    ],
    'serology' => [
        'title' => 'Serology Laboratory Result Form',
        'code' => 'SER',
        'fields' => [
            ['key'=>'dengue_duo_igg','label'=>'DENGUE DUO IgG'],
            ['key'=>'dengue_duo_igm','label'=>'DENGUE DUO IgM'],
            ['key'=>'dengue_duo_ns1','label'=>'Ns1 Ag'],
            ['key'=>'typhi_igg','label'=>'Typhidot IgG'],
            ['key'=>'typhi_igm','label'=>'Typhidot IgM'],
            ['key'=>'influenza_a','label'=>'INFLUENZA A'],
            ['key'=>'influenza_b','label'=>'INFLUENZA B'],
            ['key'=>'hbsag','label'=>'HBsAg'],
            ['key'=>'hbsab','label'=>'HBsAb'],
            ['key'=>'anti_hcv','label'=>'ANTI - HCV'],
            ['key'=>'aso_titer','label'=>'ASO TITER'],
            ['key'=>'syphilis','label'=>'SYPHILIS'],
        ],
    ],
    'misc_hiv' => [
        'title' => 'Miscellaneous Laboratory Result Form (HIV Screening)',
        'code' => 'HIV',
        'fields' => [ ['key'=>'hiv_screen','label'=>'HIV Screening Test'] ],
    ],
    'coagulation' => [
        'title' => 'Coagulation Test Result Form',
        'code' => 'COAG',
        'fields' => [
            ['key'=>'protime_patient','label'=>'PROTIME PATIENT\'S COUNT','unit'=>'sec','ref'=>'11 - 15'],
            ['key'=>'protime_control','label'=>'CONTROL COUNT','unit'=>'sec','ref'=>'12 - 14'],
            ['key'=>'activity_pct','label'=>'% ACTIVITY','unit'=>'%','ref'=>'70 - 100'],
            ['key'=>'inr','label'=>'INR','unit'=>'','ref'=>'1.0 - 1.2'],
            ['key'=>'aptt','label'=>'APTT','unit'=>'sec','ref'=>'28 - 43'],
            ['key'=>'ratio','label'=>'RATIO','unit'=>'','ref'=>'0.8 - 1.2'],
        ],
    ],
    'crossmatching' => [
        'title' => 'Crossmatching Result Form',
        'code' => 'XM',
        'fields' => [
            ['key'=>'patient_blood_type','label'=>'Patient\'s Blood Type'],
            ['key'=>'donor_blood_type','label'=>'Donor\'s Blood Type'],
            ['key'=>'blood_component','label'=>'Blood Component'],
            ['key'=>'serial_no','label'=>'Serial No.'],
            ['key'=>'extraction_date','label'=>'Extraction Date'],
            ['key'=>'packed_time','label'=>'Date & Time Packed/Thawed'],
            ['key'=>'expiration_date','label'=>'Expiration Date'],
            ['key'=>'result','label'=>'Result'],
        ],
    ],
    'thyroid' => [
        'title' => 'Thyroid Test Result Form',
        'code' => 'THY',
        'fields' => [
            ['key'=>'ft3','label'=>'fT3','unit'=>'pmol/L','ref'=>'2.8 - 7.1'],
            ['key'=>'ft4','label'=>'fT4','unit'=>'pmol/L','ref'=>'12 - 22'],
            ['key'=>'tsh','label'=>'TSH','unit'=>'mIU/L','ref'=>'0.3 - 4.2'],
        ],
    ],
    'ogtt' => [
        'title' => 'Oral Glucose Tolerance Test Result Form',
        'code' => 'OGTT',
        'fields' => [
            ['key'=>'fbs','label'=>'FBS','unit'=>'mg/dl','ref'=>'70 - 110'],
            ['key'=>'after_1h','label'=>'AFTER 1 HOUR','unit'=>'mg/dl','ref'=>'0 - 190'],
            ['key'=>'after_2h','label'=>'AFTER 2 HOURS','unit'=>'mg/dl','ref'=>'0 - 165'],
            ['key'=>'after_3h','label'=>'AFTER 3 HOURS','unit'=>'mg/dl','ref'=>'0 - 145'],
        ],
    ],
    'semen_analysis' => [
        'title' => 'Semen Analysis Result Form',
        'code' => 'SA',
        'sections' => [
            'MACROSCOPIC' => [
                ['key'=>'color','label'=>'COLOR'],
                ['key'=>'viscosity','label'=>'VISCOSITY'],
                ['key'=>'agglutination','label'=>'AGGLUTINATION'],
                ['key'=>'volume','label'=>'VOLUME'],
                ['key'=>'ph','label'=>'pH'],
                ['key'=>'specific_gravity','label'=>'SPECIFIC GRAVITY'],
                ['key'=>'liquefaction','label'=>'LIQUEFACTION TIME'],
            ],
            'MICROSCOPIC' => [
                ['key'=>'morphology_abnormal_head','label'=>'Abnormal Head'],
                ['key'=>'morphology_abnormal_tail','label'=>'Abnormal Tail'],
                ['key'=>'morphology_normal_head','label'=>'Normal Head'],
                ['key'=>'morphology_normal_tail','label'=>'Normal Tail'],
                ['key'=>'progressive_motility','label'=>'PROGRESSIVE MOTILITY'],
                ['key'=>'sperm_concentration','label'=>'SPERM CONCENTRATION'],
                ['key'=>'total_sperm_count','label'=>'TOTAL SPERM COUNT'],
                ['key'=>'leucocytes','label'=>'LEUCOCYTES'],
                ['key'=>'epithelial_cells','label'=>'EPITHELIAL CELLS'],
                ['key'=>'red_bc','label'=>'RED BLOOD CELLS'],
                ['key'=>'bacteria','label'=>'BACTERIA'],
                ['key'=>'other_cells','label'=>'OTHER CELLS'],
            ],
        ],
    ],
];
